accounts/urls.py
from accounts.views import ProfileUpdateView, ProfileView, RegisterView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile_update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("<str:username>/", ProfileView.as_view(), name="profile-detail"),
]
app_name = "accounts"

core/urls.py
from core import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("task_board.urls")),

]


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_board/urls.py
from django.urls import path

from task_board.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    AddTeamWorkerInTeamView,
    ChangeTeamWorkerIsStaffPermissionView,
    UserDeleteFromTeamView
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="project-list"),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("project/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"),
    path("project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),

    path("project/<int:pk>/task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "project/<int:pk>/task/<int:task_pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "project/<int:pk>/task/<int:task_pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "project/<int:pk>/task/<int:task_pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),

    path("teams/", TeamListView.as_view(), name="team-list"),
    path("team/create/", TeamCreateView.as_view(), name="team-create"),
    path("team/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path(
        "team/<int:pk>/add_user/",
        AddTeamWorkerInTeamView.as_view(),
        name="add-team-worker-in-team"
    ),
    path(
        "team/<int:pk>/change_permission_in_<str:slug>/",
        ChangeTeamWorkerIsStaffPermissionView.as_view(),
        name="change-team-worker-permission"
    ),
    path(
        "team/<int:pk>/delete_<str:slug>/",
        UserDeleteFromTeamView.as_view(),
        name="delete-user-from-team"
    ),
]

app_name = "task_board"

task_board/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=50)
    worker = models.ManyToManyField(
        get_user_model(),
        through="TeamWorker",
        related_name="teams"
    )

    def __str__(self):
        return self.name


class TeamWorker(models.Model):
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        related_name="team_workers"
    )
    worker = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="team_workers"
    )
    team_owner = models.BooleanField(default=False)
    team_staff = models.BooleanField(default=False)

    def clean(self) -> None:
        if self.team_owner and TeamWorker.objects.filter(
                team=self.team,
                team_owner=True
        ).exclude(worker_id=self.worker_id).exists():
            raise ValidationError("Team owner must be one")

    class Meta:
        constraints = (
            models.UniqueConstraint(fields=("team", "worker"), name="unique_worker_in_team"),
        )
        ordering = ("-team_owner", "-team_staff")


class Project(models.Model):
    name = models.CharField(max_length=100)
    team = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        null=True,
        related_name="projects"
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    class StatusChoices(models.TextChoices):
        UA = ("UA", "Unassigned")
        IP = ("IP", "In Progress")
        IR = ("IR", "In Review")
        D = ("D", "Done")

    class PriorityChoices(models.TextChoices):
        LOW = ("1", "Low Priority")
        MID = ("2", "Mid Priority")
        High = ("3", "High Priority")

    name = models.CharField(max_length=100)
    description = models.TextField()
    deadline = models.DateTimeField()
    priority = models.CharField(max_length=1, choices=PriorityChoices.choices)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="tasks")
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True)
    status = models.CharField(max_length=2, choices=StatusChoices.choices)
    assignees = models.ManyToManyField(get_user_model(), related_name="tasks", blank=True)
    task_type = models.ForeignKey(
        TaskType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="tasks"
    )

    def __str__(self):
        return self.name

task_board/forms.py
from django import forms
from django.contrib.auth import get_user_model

from task_board.models import Project, Task, Team


class ProjectForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.fields["team"].queryset = Team.objects.filter(
            team_workers__worker=user,
            team_workers__team_owner=True
        )

    class Meta:
        model = Project
        fields = ["name", "team"]


class TaskForm(forms.ModelForm):
    def __init__(self, project_pk, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields["assignees"].queryset = get_user_model().objects.filter(
            team_workers__team__projects__pk=project_pk
        )

    class Meta:
        model = Task
        fields = [
            "name", "description", "deadline", "priority", "task_type", "tags", "assignees"
        ]


class TeamUpdateForm(forms.Form):
    email = forms.EmailField()

task_board/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from task_board.forms import ProjectForm, TaskForm, TeamUpdateForm
from task_board.models import Project, Task, Team, TeamWorker
from task_board.permissions import (
    TeamStaffOrOwnerRequiredMixin,
    UserInTeamProjectRequiredMixin,
    UserInTeamTeamRequiredMixin,
    UserTeamOwnerProjectRequiredMixin,
    UserTeamOwnerTeamRequiredMixin
)


class ProjectListView(
    LoginRequiredMixin,
    generic.ListView
):
    def get_queryset(self):
        return Project.objects.filter(team__worker=self.request.user).select_related("team")


class ProjectDetailView(
    LoginRequiredMixin,
    generic.DetailView
):
    def get_queryset(self):
        return Project.objects.filter(
            team__worker=self.request.user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team_worker = TeamWorker.objects.get(
            team__projects__pk=self.kwargs["pk"],
            worker=self.request.user
        )
        context["is_owner"] = team_worker.team_owner
        context["is_staff"] = team_worker.team_staff
        context["tasks"] = context["object"].tasks.order_by(
            "deadline", "-priority"
        ).select_related(
            "task_type"
        ).prefetch_related(
            "tags", "assignees"
        )
        return context


class ProjectCreateView(
    LoginRequiredMixin,
    generic.CreateView
):
    form_class = ProjectForm
    template_name = "task_board/project_form.html"

    def get_success_url(self):
        return reverse("task_board:project-detail", kwargs={"pk": self.object.pk})

    def get_form_kwargs(self):
        kwargs = super(ProjectCreateView, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ProjectUpdateView(
    LoginRequiredMixin,
    UserTeamOwnerProjectRequiredMixin,
    generic.UpdateView
):
    model = Project
    fields = ("name",)

    def get_success_url(self):
        return reverse("task_board:project-detail", kwargs={"pk": self.object.pk})


class ProjectDeleteView(
    LoginRequiredMixin,
    UserTeamOwnerProjectRequiredMixin,
    generic.DeleteView
):
    model = Project
    success_url = reverse_lazy("task_board:project-list")


class TaskCreateView(
    LoginRequiredMixin,
    TeamStaffOrOwnerRequiredMixin,
    generic.CreateView
):
    model = Task
    form_class = TaskForm
    template_name = "task_board/task_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_pk"] = self.kwargs["pk"]
        return context

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs["project_pk"] = self.kwargs["pk"]
        return kwargs

    def form_valid(self, form):
        ip = Task.StatusChoices.IP
        ua = Task.StatusChoices.UA

        form.instance.project = get_object_or_404(Project, pk=self.kwargs["pk"])
        form.instance.status = ip if form.cleaned_data.get("assignees") else ua
        return super(TaskCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse("task_board:project-detail", kwargs={"pk": self.object.project.pk})


class TaskDetailView(
    LoginRequiredMixin,
    UserInTeamProjectRequiredMixin,
    generic.DetailView
):
    def get_object(self, queryset=None):
        return get_object_or_404(
            Task,
            project__pk=self.kwargs["pk"],
            pk=self.kwargs["task_pk"]
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team_worker = TeamWorker.objects.get(
            team__projects__pk=self.kwargs["pk"],
            worker=self.request.user
        )
        context["is_owner"] = team_worker.team_owner
        context["is_staff"] = team_worker.team_staff
        return context


class TaskUpdateView(
    LoginRequiredMixin,
    TeamStaffOrOwnerRequiredMixin,
    generic.UpdateView
):
    model = Task
    fields = (
        "name",
        "description",
        "deadline",
        "priority",
        "task_type",
        "tags",
        "status",
        "assignees"
    )
    template_name = "task_board/task_form.html"

    def get_object(self, queryset=None):
        return get_object_or_404(
            Task,
            project__pk=self.kwargs["pk"],
            pk=self.kwargs["task_pk"]
        )

    def get_success_url(self):
        return reverse("task_board:project-detail", kwargs={"pk": self.object.project.pk})


class TaskDeleteView(
    LoginRequiredMixin,
    TeamStaffOrOwnerRequiredMixin,
    generic.DeleteView
):
    model = Task
    template_name = "task_board/task_confirm_delete.html"

    def get_success_url(self):
        return reverse("task_board:project-detail", kwargs={"pk": self.object.project.pk})

    def get_object(self, queryset=None):
        return get_object_or_404(
            Task,
            project__pk=self.kwargs["pk"],
            pk=self.kwargs["task_pk"]
        )


class TeamListView(
    LoginRequiredMixin,
    generic.ListView
):

    def get_queryset(self):
        return Team.objects.filter(
            team_workers__worker=self.request.user
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = context["object_list"].values(
            "pk", "name", "team_workers__team_owner", "team_workers__team_staff"
        )
        return context


class TeamCreateView(
    LoginRequiredMixin,
    generic.CreateView
):
    model = Team
    fields = ("name", )
    template_name = "task_board/team_form.html"

    def get_success_url(self):
        return reverse("task_board:team-detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        response = super().form_valid(form)
        TeamWorker.objects.create(
            team=self.object,
            worker=self.request.user,
            team_owner=True
        )
        return response


class TeamDetailView(
    LoginRequiredMixin,
    UserInTeamTeamRequiredMixin,
    generic.DetailView
):
    template_name = "task_board/team_detail.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Team, pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["team_workers"] = TeamWorker.objects.filter(
            team=context["object"]
        ).select_related("worker", "worker__position")
        context["is_owner"] = context["team_workers"].get(
            team=context["object"],
            worker=self.request.user
        ).team_owner
        return context


class AddTeamWorkerInTeamView(
    LoginRequiredMixin,
    UserTeamOwnerTeamRequiredMixin,
    generic.FormView
):
    form_class = TeamUpdateForm
    template_name = "task_board/team_form.html"

    def get_success_url(self):
        return reverse("task_board:team-detail", kwargs={"pk": self.kwargs["pk"]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"] = get_object_or_404(
            Team.objects.values("name", "pk"),
            pk=self.kwargs["pk"]
        )
        return context

    def form_valid(self, form):
        user_to_add = get_object_or_404(get_user_model(), email=form.cleaned_data["email"])
        team = get_object_or_404(Team, pk=self.kwargs["pk"])
        TeamWorker.objects.create(team=team, worker=user_to_add)
        return super(AddTeamWorkerInTeamView, self).form_valid(form)


class ChangeTeamWorkerIsStaffPermissionView(
    LoginRequiredMixin,
    UserTeamOwnerTeamRequiredMixin,
    generic.UpdateView
):
    model = TeamWorker
    fields = ("team_staff",)
    template_name = "task_board/change_permission_in_team_form.html"

    def get_success_url(self):
        return reverse("task_board:team-detail", kwargs={"pk": self.kwargs["pk"]})

    def get_object(self, queryset=None):
        return get_object_or_404(
            TeamWorker,
            team__pk=self.kwargs["pk"],
            worker__username=self.kwargs["slug"]
        )


class UserDeleteFromTeamView(
    LoginRequiredMixin,
    UserTeamOwnerTeamRequiredMixin,
    generic.DeleteView
):
    model = TeamWorker
    template_name = "task_board/team_confirm_delete.html"

    def get_object(self, queryset=None):
        return get_object_or_404(
            TeamWorker,
            team__pk=self.kwargs["pk"],
            worker__username=self.kwargs["slug"]
        )

    def get_success_url(self):
        if self.object.team_owner:
            return reverse("task_board:team-list")
        else:
            return reverse(
                "task_board:team-detail",
                kwargs={"pk": self.object.team.pk}
            )

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.object.team_owner:
            team_workers = TeamWorker.objects.filter(team=self.object.team)
            if team_workers.exists():
                team_staff = team_workers.filter(team_staff=True)
                if team_staff:
                    team_staff_first = team_staff.first()
                    team_staff_first.team_owner = True
                    team_staff_first.save()
                else:
                    team_workers_first = team_workers.first()
                    team_workers_first.team_owner = True
                    team_workers_first.save()
            else:
                self.object.team.delete()
        return response

templates/task_board/change_permission_in_team_form.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>Change {{ object.name }} permissions</h1>
  <form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-primary">
  <a class="btn btn-primary" href="{% url 'task_board:team-detail' object.team.pk %}">Cancel</a>
  </form>
{% endblock %}

templates/task_board/project_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Project "{{ object.name }}"?</h2>
  <form method="post">
  {% csrf_token %}
  <input type="submit" value="accept" class="btn btn-danger">
  <a class="btn btn-primary" href="{% url 'task_board:project-detail' object.pk %}">Cancel</a>
  </form>
{% endblock %}

templates/task_board/project_form.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>{{ object|yesno:"Update,Create" }} project</h1>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary">
    {% if object %}
      <a class="btn btn-primary" href="{% url 'task_board:project-detail' object.pk %}">Cancel</a>
    {% else %}
      <a class="btn btn-primary" href="{% url 'task_board:project-list' %}">Cancel</a>
    {% endif %}
  </form>
{% endblock %}

templates/task_board/project_list.html
{% extends 'base.html' %}
{% block content %}
  <a href="{% url 'task_board:project-create' %}">
    <button class="btn btn-primary mt-2 mb-3">Create new project</button>
  </a>
  {% for project in object_list %}
    <p>
      <a href="{% url 'task_board:project-detail' project.id %}">{{ project.name }}</a>
      by {{ project.team.name }}
    </p>
  {% endfor %}
{% endblock %}

templates/task_board/task_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Task "{{ object.name }}"?</h2>
  <form method="post">
  {% csrf_token %}
  <input type="submit" value="accept" class="btn btn-danger">
  <a class="btn btn-primary" href="{% url 'task_board:task-detail' object.project.pk object.pk %}">Cancel</a>
  </form>
{% endblock %}

templates/task_board/task_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="card">
    <div class="card-header">
      Task detail
    </div>
    <div class="card-body">
      <h5 class="card-title">
        {{ object.name }} from
        <a href="{% url 'task_board:project-detail' object.project.pk %}">
          {{ object.project }}
        </a>
      </h5>
      <p class="card-text">{{ object.description }}</p>
      <p class="card-text">{{ object.deadline }}</p>
      <p class="card-text">{{ object.get_priority_display }}</p>
      <p class="card-text">{{ object.get_status_display }}</p>
      <p class="card-text">{{ object.task_type }}</p>
      <p class="card-text">
        Tags:
      <ul>
        {% for tag in object.tags.all %}
          <li>{{ tag.name }}</li>
        {% endfor %}
      </ul>
      </p>
      <p class="card-text">
        Assignees:
      <ul>
        {% for assign in object.assignees.all %}
          <li><a href="{% url 'accounts:profile-detail' assign.username %}">{{ assign.username }}</a></li>
        {% endfor %}
      </ul>
      </p>
      {% if is_owner or is_team_staff %}
        <a href="{% url 'task_board:task-update' object.project.pk task.pk %}" class="btn btn-primary">Update</a>
        <a href="{% url 'task_board:task-delete' object.project.pk task.pk %}" class="btn btn-danger">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/task_board/task_form.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-primary">
      {% if object %}
      <a class="btn btn-primary" href="{% url 'task_board:task-detail' object.project.pk object.pk %}">Cancel</a>
    {% else %}
        <a class="btn btn-primary" href="{% url 'task_board:project-detail' project_pk %}">Cancel</a>
    {% endif %}
  </form>
{% endblock %}

templates/task_board/team_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete "{{ object.worker.username }}" from {{ object.team.name }}?</h2>
  <form method="post">
  {% csrf_token %}
  <input type="submit" value="accept" class="btn btn-danger">
  <a class="btn btn-primary" href="{% url 'task_board:team-detail' object.team.pk %}">Cancel</a>
  </form>
{% endblock %}

templates/task_board/team_detail.html
{% extends 'base.html' %}
{% block content %}
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <div class="bg-white py-24 sm:py-32">
    <div class="mx-auto grid max-w-7xl gap-x-8 gap-y-20 px-6 lg:px-8 xl:grid-cols-3">
      <div class="max-w-2xl">
        <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Meet our {{ object.name }} team
          members</h2>
        {% if is_owner %}
          <a href="{% url 'task_board:add-team-worker-in-team' object.pk %}">
            <button class="btn btn-primary">Add user</button>
          </a>
        {% endif %}
      </div>
      <ul role="list" class="grid gap-x-8 gap-y-12 sm:grid-cols-2 sm:gap-y-16 xl:col-span-2">
        {% for team_worker in team_workers %}
          <li>
            <div class="flex items-center gap-x-6">
              <img class="h-16 w-16 rounded-full"
                      {% if team_worker.worker.profile_picture %}
                   src="{{ team_worker.worker.profile_picture.url }}"
                      {% endif %}
                   alt="">
              <div>
                <h3 class="text-base font-semibold leading-7 tracking-tight text-gray-900">
                  <a href="{% url 'accounts:profile-detail' team_worker.worker.username %}">
                    {{ team_worker.worker.username }}
                  </a>
                </h3>
                <p class="text-sm font-semibold leading-6 text-indigo-600">{{ team_worker.worker.position }}
                  {% if team_worker.team_owner %}
                    / team owner
                  {% elif team_worker.team_staff %}
                    / team staff
                  {% endif %}
                </p>
                {% if is_owner %}
                  <a href="{% url 'task_board:change-team-worker-permission' object.pk team_worker.worker.username %}">
                    <button class="btn btn-primary">Change</button>
                  </a>
                  <a href="{% url 'task_board:delete-user-from-team' object.pk team_worker.worker.username %}">
                    <button class="btn btn-dangeon">Delete</button>
                  </a>
                {% endif %}
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

templates/task_board/team_form.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_filters %}
  <h1>{{ object|yesno:"Add in,Create" }} team {{ object.name }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-primary">
    {% if object %}
      <a class="btn btn-primary" href="{% url 'task_board:team-detail' object.pk %}">Cancel</a>
    {% else %}
      <a class="btn btn-primary" href="{% url 'task_board:team-list' %}">Cancel</a>
    {% endif %}
  </form>
{% endblock %}

templates/task_board/team_list.html
{% extends 'base.html' %}
{% block content %}
  <a href="{% url 'task_board:team-create' %}"><button class="btn btn-primary">Create team</button></a>
  <ul>
    {% for team in object_list %}
      <li>
        <a href="{% url 'task_board:team-detail' team.pk %}">
          {{ team.name }}
        </a>
        {% if team.team_workers__team_owner %}
          (owner)
        {% elif team.team_workers__team_staff %}
          (staff)
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}