accounts/urls.py
from accounts.views import ProfileUpdateView, ProfileView, RegisterView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile_update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("<str:username>/", ProfileView.as_view(), name="profile-detail"),
]
app_name = "accounts"

core/urls.py
from core import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("task_board.urls")),

]


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_board/urls.py
from django.urls import path

from task_board.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    AddTeamWorkerInTeamView,
    ChangeTeamWorkerIsStaffPermissionView,
    UserDeleteFromTeamView
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="project-list"),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("project/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"),
    path("project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),

    path("project/<int:pk>/task/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "project/<int:pk>/task/<int:task_pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "project/<int:pk>/task/<int:task_pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "project/<int:pk>/task/<int:task_pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),

    path("teams/", TeamListView.as_view(), name="team-list"),
    path("team/create/", TeamCreateView.as_view(), name="team-create"),
    path("team/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path(
        "team/<int:pk>/add_user/",
        AddTeamWorkerInTeamView.as_view(),
        name="add-team-worker-in-team"
    ),
    path(
        "team/<int:pk>/change_permission_in_<str:slug>/",
        ChangeTeamWorkerIsStaffPermissionView.as_view(),
        name="change-team-worker-permission"
    ),
    path(
        "team/<int:pk>/delete_<str:slug>/",
        UserDeleteFromTeamView.as_view(),
        name="delete-user-from-team"
    ),
]

app_name = "task_board"

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}

    <li class="list-group-item">User: <a href="{% url 'accounts:profile-detail' user.get_username %}">
      {% if user.profile_picture %}
      <img src="{{ user.profile_picture.url }}" width="50" height="50"> 
        {% endif %}
    {{ user.get_username }}
    </a></li>
    <li class="list-group-item"><a href="{% url 'accounts:logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'accounts:login'%}?next={{request.path}}">Login</a></li>
    <li class="list-group-item"><a href="{% url 'accounts:register'%}?next={{request.path}}">Sign-up</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'task_board:project-list' %}">Projects</a></li>
  <li class="list-group-item"><a href="{% url 'task_board:team-list' %}">Teams</a></li>
</ul>